server:
  address: 0.0.0.0
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  profiles:
    default: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: stream-guppy
  docker:
    compose:
      lifecycle-management: start-and-stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m
      file: docker-compose.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

stream_guppy:
  ffmpeg:
#    path: ./ffmpeg/ffmpeg # MacOS
    path: ./ffmpeg/ffmpeg.exe # Windows
    waitForM3u8TimeoutSeconds: 30
  hls:
    output:
      basePath: ./hls_output
  streaming:
    inactivityTimeoutSeconds: 60
  # Database configuration (h2, oracle, mssql, postgresql, mysql, mariadb)
  database: h2

  # Oracle database configuration
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: system
      password: password

    # Microsoft SQL Server configuration
    mssql:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databaseName=stream_guppy;encrypt=false
      username: sa
      password: password

    # PostgreSQL configuration
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/stream_guppy
      username: postgres
      password: password

    # MySQL configuration
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/stream_guppy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: password

    # MariaDB configuration
    mariadb:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/stream_guppy
      username: root
      password: password

  frontUrl: "http://localhost:8080"
